### ISSUE TITLE
How to build and run

### ISSUE THREAD

**Issue by hfye** [ArkCase/ArkCase#1]
Hi, is there any build and installation guide?

**Comment by david-oc-miller** [comment]
@hfye, it took much, much longer than I expected to cleanse our existing code of proprietary and non-open-source components, but I think we are finally there.  Check these three repositories for a guide, in case you are still interested these many months later.

ArkCase source code: https://github.com/ArkCase/ArkCase

ArkCase configuration: https://github.com/ArkCase/.arkcase

ArkCase virtual machine: https://github.com/ArkCase/arkcase-ce

--
Dave
