### ISSUE TITLE
incorrect sed command in README instructions

### ISSUE THREAD

**Issue by DavidBiesack** [ArkCase/ArkCase#18]
The main README says:
```
Run this command: sed 's|127.0.0.1 arkcase-host|172.28.128.1|g' /etc/hosts, being careful to replace
172.28.128.1 with the IP address you identified above. It will output the updated text, 
but will not actually update /etc/hosts:
```
This is incorrect (although correct in the next example). The `sed` command omits the "  arkcase-host" in the replacement text and should be

```
sed 's|127.0.0.1 arkcase-host|172.28.128.1 arkcase-host|g' /etc/hosts
``

**Comment by david-oc-miller** [comment]
This broken `sed` command is in the `master` branch which is orphaned, possibly we should remove it soon.  The `main` branch is active now and doesn't include any `sed` commands.  I am closing this issue as overtaken by events.
