### ISSUE TITLE
Extending ArkCase to include Suspects module

### ISSUE THREAD

**Issue by jj1161** [ArkCase/ArkCase#33]
Currently in ArkCase, the People's module does not distinguish between the subject of the complaint and the investigator investigating the complaint. This functionality would be needed if ArkCase is used for a more criminal investigation usage.

High level the requirement is to have a distinction between internal employees conducting the review/investigation and external suspects that are being investigated. As an example - a Complaint will have assigned People similar to today's existing People module functionality which are registered users in the system with a login, roles and privileges to investigate the complaint. Within the complaint, there will be investigated suspects that are subjects in the complaint and are not part of the People's list.

My questions are:
1. To implement such functionality does it make sense to develop a plugin as described in this page: https://arkcase.atlassian.net/wiki/spaces/AD/pages/1647738881/Tutorial+Extending+ArkCase, creating a new Suspects module in the system? Maybe as an extension to People's module?
2. If this feature is not fit for developing as a plugin, can you recommend a better way of implementing it? It will have many similarities to the People module.
3. Is this an interesting enhancement you would be interested in adding to ArkCase?  

Thanks

**Comment by david-oc-miller** [comment]
@jj1161 ,

The internal employees working on a case file or complaint or task, should be tracked as participants.  Each participant has a role that gives them some level of access.  You wouldn't use the people list to manage internal users working on an object.

The people list is to track people associated to the object in the real world (suspects, witnesses, people of interest etc).

Our user guide documents some of this.  https://www.arkcase.com/adding-complaint-content/ shows how to manage people and how to manage participants on a complaint.  The screen shot at https://www.arkcase.com/treeview-of-a-complaint/ shows the people node and the participants node, within the nodes available on complaints.

Does that make sense?  Given the separate modules for participants and people, does that allow you to do what you need?

Thanks,
Dave

**Comment by jj1161** [comment]
When clicking on the People's module the list shows all users in the system, this includes Admin users and LDAP users as well as suspects.

This list is also available when opening a complaint, it is possible to choose the internal users (Admin and LDAP) as People (suspects, witnesses, people of interest) of the complaint. For example this is the popup used to add People to a complaint:
![image](https://user-images.githubusercontent.com/96937598/149198388-a7dbcfd8-f463-4514-8cce-c6940c3a0f91.png)

Is it possible to filter the People's list so that the systems users do not appear?
If this is possible then the seperate modules for participants and people is good.

**Comment by jj1161** [comment]
I am assuming People and Person are the same entity in the system. Is this correct?

**Comment by david-oc-miller** [comment]
@jj1161 , the fact that all application users are also people in the People module, seems to be relatively recent, and it doesn't make sense for most customers, as you have observed.  I'm going to find out if there's a feature flag to control this; and if there isn't such a flag, I'll have to write a ticket for it and add it to our current sprint.

"People" and "Person" are the same (the People module manages Persons).  People and participants are different (persons versus users).

**Comment by david-oc-miller** [comment]
It seems this code is from May 2021 and there is no feature flag to control it.

The Person entity has an attribute `ldapUserId`, if this attribute is set, the Person is a user.  If not set, the person is not a user.  I'm not sure how this could help you though.  

The relevant code is in https://github.com/ArkCase/ArkCase/blob/master/acm-plugins/acm-default-plugins/acm-person-plugin/src/main/java/com/armedia/acm/plugins/person/service/CreatePersonFromUser.java.

I'll be working with my development team to see how we can address this.

**Comment by david-oc-miller** [comment]
In the issue https://github.com/ArkCase/arkcase-ce/issues/370 I showed how to deploy an updated arkcase.war.  You could update the CreatePersonFromUser class to not take any action (either return immediately or just remove the calls that create the Person). 

We should release 2021.03.01 soon which will include the new feature flag, but "soon" may be a week or two.  See ticket https://arkcase.atlassian.net/browse/ACFP-1545.

**Comment by jj1161** [comment]
I will wait for the next release for this fix.
Thanks for the assistance and all the information.
