### ISSUE TITLE
Phone number format fixed to xxx-xxx-xxxx may be not suitable in other countries

### ISSUE THREAD

**Issue by kcleung** [ArkCase/ArkCase#9]
I am testing out the arkcase VM 3.3.1-r1-a

When I tried to add a person, the telephone refuses to take phone numbers that are not in the following format:

xxx-xxx-xxxx

However, when you work outside the United States, the number of digits are often different.  This makes recording phone number impossible for clients residing outside the United States.

This is a UI showstopper that must be fixed immediately.

**Comment by david-oc-miller** [comment]
Hi @kcleung, thanks for sending this issue.  I will try to get back to you with a resolution soon.

**Comment by david-oc-miller** [comment]
@kcleung , to finally close the loop on this, the phone number pattern is in system configuration.  In the home folder of the ArkCase user, change to the .arkcase/acm/acm-config-server folder, and look for the key `phone_regex`.  This changes the phone number pattern everywhere.

We have an improvement ticket to specify per-country phone number patterns, but work has not started on this ticket: https://arkcase.atlassian.net/browse/ACFP-11.
